/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package Zifratu;

import java.util.Random;

public class App {

    public String alfabetoa="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    public String gakoa;
    public App(String gakoa){
        this.gakoa=gakoa;
    }
    public static void main(String[] args) {
        zifratu1();
    }


    public static void zifratu1(){
        String gakoa="ZXCVBNMASDFGHJKLQWERTYUIOP";
        String mezua = "EZ GAUDE GERRAREN ALDE";
        App probak = new App(gakoa);
        System.out.println();
        System.out.println("Orain defektuzko gakoaz zifratuko dugu");
        System.out.println("Hurrengo mezua zifratuko da: "+ mezua);
        System.out.println("Alfabeto hau erabiliz: "+ probak.gakoa);
        System.out.println("Eta lortu dugun mezu zifratua honakoa da: "+probak.zifratu(mezua));

        System.out.println();
        System.out.println("Orain zorizko gako batekin zifratuko dugu");
        probak.generatuGakoa();
        System.out.println("Hurrengo mezua zifratuko da: "+ mezua);
        System.out.println("Alfabeto hau erabiliz: "+ probak.gakoa);
        System.out.println("Eta lortu dugun mezu zifratua honakoa da: "+probak.zifratu(mezua));
    }

    public void generatuGakoa(){
        String gakoRandom="";
        int lenght = alfabetoa.length();
        Random random = new Random();
        char unekoChar;
        //ºint zikloKop=0;
        while(lenght>gakoRandom.length()){
            StringBuilder sb = new StringBuilder(alfabetoa);
            int unekoa = random.nextInt(alfabetoa.length());
            unekoChar=alfabetoa.charAt(unekoa);
            gakoRandom+=unekoChar;
            sb.deleteCharAt(unekoa);
            alfabetoa=sb.toString();
           // zikloKop++;
        }
        //System.out.println(zikloKop + " ziklo egin ditu");
        this.gakoa=gakoRandom;
    }
    private String zifratu(String mezua){
        String emaitza="";
        for(int i=0;i<mezua.length();i++){
            if(this.alfabetoa.contains(""+mezua.charAt(i))){
                emaitza+=this.gakoa.charAt(this.alfabetoa.indexOf(mezua.charAt(i)));
            }else{
                emaitza+=mezua.charAt(i);
            }
        }
        return emaitza;
    }
}
