/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package Zifratu;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.Random;

public class App {

    public String alfabetoa;
    public String mezua;
    public String gakoa;

    public App(String gakoa, String alfa, String mezua){
        this.alfabetoa= alfa;
        this.mezua= mezua;
        this.gakoa=gakoa;
    }
    public static void main(String[] args) {
        String alfa = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
        String gakoa="ZXCVBNMASDFGHJKLQWERTYUIOP";
        String mezua = "EZ GAUDE GERRAREN ALDE";
        zifratu1(gakoa, alfa, mezua);
    }


    public static void zifratu1(String gakoa, String alfa, String mezua){
        App lehenetsia = new App(gakoa,alfa,mezua);
        System.out.println("Hurrengo mezua zifratuko da: "+ lehenetsia.mezua);
        System.out.println("Alfabeto hau erabiliz: "+ lehenetsia.gakoa);
        System.out.println("Eta lortu dugun mezu zifratua honakoa da: "+lehenetsia.zifratu());
        App randomGakoa= new App(" ",alfa,mezua);
        randomGakoa.generatuGakoa(alfa);
        System.out.println("Hurrengo mezua zifratuko da: "+ randomGakoa.mezua);
        System.out.println("Alfabeto hau erabiliz: "+ randomGakoa.gakoa);
        System.out.println("Eta lortu dugun mezu zifratua honakoa da: "+randomGakoa.zifratu());
    }

    public void generatuGakoa(String alfabetoa){
        String gakoRandom="";
        int lenght = alfabetoa.length();
        Random random = new Random();
        char unekoChar;
        int zikloKop=0;
        while(lenght>gakoRandom.length()){
            StringBuilder sb = new StringBuilder(alfabetoa);
            int unekoa = random.nextInt(alfabetoa.length());
            unekoChar=alfabetoa.charAt(unekoa);
            gakoRandom+=unekoChar;
            sb.deleteCharAt(unekoa);
            alfabetoa=sb.toString();
            System.out.println(gakoRandom + " da gakoa eta honakoa caracterea: " +unekoChar);
            zikloKop++;
        }
        System.out.println(zikloKop + " ziklo egin ditu");
        this.gakoa=gakoRandom;
    }
    private String zifratu(){
        String emaitza="";
        for(int i=0;i<this.mezua.length();i++){
            if(this.alfabetoa.contains(""+this.mezua.charAt(i))){
                emaitza+=this.gakoa.charAt(this.alfabetoa.indexOf(this.mezua.charAt(i)));
            }else{
                emaitza+=this.mezua.charAt(i);
            }
        }


        return emaitza;

    }
}
